version: "1"
services:
  mongodb-services:
    image: mongo:latest
    container_name: mongodb-services
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  services-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: services-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb-services
